export const darkMapStyle = [
  { elementType: 'geometry', stylers: [{ color: '#1B1B1E' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#1B1B1E' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#757575' }] },
  { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#B3B3B3' }] },
  { featureType: 'poi', elementType: 'labels.text.fill', stylers: [{ color: '#757575' }] },
  { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#18181A' }] },
  { featureType: 'poi.park', elementType: 'labels.text.fill', stylers: [{ color: '#6B6B6B' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#2C2C2E' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#212121' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#8A8A8A' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#3C3C3E' }] },
  { featureType: 'road.highway', elementType: 'geometry.stroke', stylers: [{ color: '#1F1F1F' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#A1A1AA' }] },
  { featureType: 'transit', elementType: 'geometry', stylers: [{ color: '#2F2F2F' }] },
  { featureType: 'transit.station', elementType: 'labels.text.fill', stylers: [{ color: '#8A8A8A' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#09090B' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#3D3D3D' }] },
  { featureType: 'water', elementType: 'labels.text.stroke', stylers: [{ color: '#17263C' }] },
];
